version: '3'

services:
  node:
    # Build a container based on customized Dockerfile image
    build: 
      dockerfile: ./Dockerfile
      context: .
    container_name: talker_manager
    restart: always
    # execution standart directory
    working_dir: /app
    volumes:
      # Maps the current dirctory, with all data, to directory /app in the container
      - ./:/app
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: database
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${DB_NAME}
    # Inialize this container after the database container is up.
    depends_on:
      database:
        condition: service_healthy  
  database:
    container_name: talker_manager_db
    image: mysql:8.0.32
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    # env_file:
    #   - .env
    healthcheck:
      # test if the MySQL server is responding
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - "3306:3306"
    # Mounts the SQL script into the container so it runs automatically at database initialization
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql